[package]
name = "model-catalog"
version = "0.1.0"
edition = "2021"

[features]
default = ["burn/default"]

[dependencies]
burn = { version = "0.12.1", features = ["train", "wgpu", "vision"] }
clap = { version = "4.5.3", features = ["derive"] }

